/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.client.doctor.api;

import com.bytatech.ayoos.client.doctor.model.HospitalDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-04-18T10:03:07.389+05:30[Asia/Calcutta]")

@Api(value = "HospitalResource", description = "the HospitalResource API")
public interface HospitalResourceApi {

    @ApiOperation(value = "createHospital", nickname = "createHospitalUsingPOST", notes = "", response = HospitalDTO.class, tags={ "hospital-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = HospitalDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/hospitals",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<HospitalDTO> createHospitalUsingPOST(@ApiParam(value = "hospitalDTO" ,required=true )  @Valid @RequestBody HospitalDTO hospitalDTO);


    @ApiOperation(value = "deleteHospital", nickname = "deleteHospitalUsingDELETE", notes = "", tags={ "hospital-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/hospitals/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteHospitalUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllHospitals", nickname = "getAllHospitalsUsingGET", notes = "", response = HospitalDTO.class, responseContainer = "List", tags={ "hospital-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = HospitalDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/hospitals",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<HospitalDTO>> getAllHospitalsUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getHospital", nickname = "getHospitalUsingGET", notes = "", response = HospitalDTO.class, tags={ "hospital-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = HospitalDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/hospitals/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<HospitalDTO> getHospitalUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchHospitals", nickname = "searchHospitalsUsingGET", notes = "", response = HospitalDTO.class, responseContainer = "List", tags={ "hospital-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = HospitalDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/hospitals",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<HospitalDTO>> searchHospitalsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateHospital", nickname = "updateHospitalUsingPUT", notes = "", response = HospitalDTO.class, tags={ "hospital-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = HospitalDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/hospitals",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<HospitalDTO> updateHospitalUsingPUT(@ApiParam(value = "hospitalDTO" ,required=true )  @Valid @RequestBody HospitalDTO hospitalDTO);

}
